#! /bin/sh
### BEGIN INIT INFO
# Provides:          Projeto Final
# Required-Start:
# Should-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Configura GPIO, PWM e SPI para o Projeto Final.
# Description:       Configura GPIO, PWM e SPI para o Projeto Final.
# Beuren Bechlin, Gabriel Ammes, Thiago Martins
### END INIT INFO

case "$1" in
    start|restart|force-reload)
	##############################################################
        # IO3 (PWM) *
	if [ ! -d /sys/class/pwm/pwmchip0/pwm1 ] ; then
	    echo -n "1" > /sys/class/pwm/pwmchip0/export
	fi
	chgrp pwm /sys/class/pwm/pwmchip0/device/pwm_period
	chmod g+w /sys/class/pwm/pwmchip0/device/pwm_period
	chgrp pwm /sys/class/pwm/pwmchip0/pwm1/duty_cycle
	chmod g+w /sys/class/pwm/pwmchip0/pwm1/duty_cycle
	chgrp pwm /sys/class/pwm/pwmchip0/pwm1/enable
	chmod g+w /sys/class/pwm/pwmchip0/pwm1/enable

        # gpio16 = 0 = out
	if [ ! -d /sys/class/gpio/gpio16 ] ; then
	    echo -n "16" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio16/direction
	echo -n "0" > /sys/class/gpio/gpio16/value

        # gpio17 = in = no pull-up nor pull-down
	if [ ! -d /sys/class/gpio/gpio17 ] ; then
	    echo -n "17" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio17/direction

        # gpio76 = 0
	if [ ! -d /sys/class/gpio/gpio76 ] ; then
	    echo -n "76" > /sys/class/gpio/export
	fi
	echo -n "0" > /sys/class/gpio/gpio76/value

        # gpio64 = 1 */
	if [ ! -d /sys/class/gpio/gpio64 ] ; then
	    echo -n "64" > /sys/class/gpio/export
	fi
	echo -n "1" > /sys/class/gpio/gpio64/value

	##############################################################
	# IO4 (SAÍDA) *
	if [ ! -d /sys/class/gpio/gpio6 ] ; then
	    echo -n "6" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio6/direction
	chgrp gpio /sys/class/gpio/gpio6/value
	chmod g+rw /sys/class/gpio/gpio6/value

	# Level Shifter GPIO
	if [ ! -d /sys/class/gpio/gpio36 ] ; then
	    echo -n "36" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio36/direction
	echo -n "0" > /sys/class/gpio/gpio36/value

	##############################################################
	# IO5 (ENTRADA) *
	if [ ! -d /sys/class/gpio/gpio0 ] ; then
	    echo -n "0" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio0/direction
	chgrp gpio /sys/class/gpio/gpio0/value
	chmod g+rw /sys/class/gpio/gpio0/value

	# Level Shifter GPIO
	if [ ! -d /sys/class/gpio/gpio18 ] ; then
	    echo -n "18" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio18/direction
	echo -n "1" > /sys/class/gpio/gpio18/value

	# Pin Mux 1 GPIO
	if [ ! -d /sys/class/gpio/gpio66 ] ; then
	    echo -n "66" > /sys/class/gpio/export
	fi
	echo -n "0" > /sys/class/gpio/gpio66/value

	##############################################################
	# IO6 (ENTRADA) *
	if [ ! -d /sys/class/gpio/gpio1 ] ; then
	    echo -n "1" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio1/direction
	chgrp gpio /sys/class/gpio/gpio1/value
	chmod g+rw /sys/class/gpio/gpio1/value

	# Level Shifter GPIO
	if [ ! -d /sys/class/gpio/gpio20 ] ; then
	    echo -n "20" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio20/direction
	echo -n "1" > /sys/class/gpio/gpio20/value

	# Pin Mux 1 GPIO
	if [ ! -d /sys/class/gpio/gpio68 ] ; then
	    echo -n "68" > /sys/class/gpio/export
	fi
	echo -n "0" > /sys/class/gpio/gpio68/value

	##############################################################
	# IO7 (SAÍDA) *
	if [ ! -d /sys/class/gpio/gpio38 ] ; then
	    echo -n "38" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio38/direction
	chgrp gpio /sys/class/gpio/gpio38/value
	chmod g+rw /sys/class/gpio/gpio38/value

	##############################################################
	# IO8 (SAÍDA) *
	if [ ! -d /sys/class/gpio/gpio40 ] ; then
	    echo -n "40" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio40/direction
	chgrp gpio /sys/class/gpio/gpio40/value
	chmod g+rw /sys/class/gpio/gpio40/value

	##############################################################
	# IO9 (SAÍDA) *
	if [ ! -d /sys/class/gpio/gpio4 ] ; then
	    echo -n "4" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio4/direction
	chgrp gpio /sys/class/gpio/gpio4/value
	chmod g+rw /sys/class/gpio/gpio4/value

	# Level Shifter GPIO
	if [ ! -d /sys/class/gpio/gpio22 ] ; then
	    echo -n "22" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio22/direction
	echo -n "0" > /sys/class/gpio/gpio22/value

	# Pin Mux 1 GPIO
	if [ ! -d /sys/class/gpio/gpio70 ] ; then
	    echo -n "70" > /sys/class/gpio/export
	fi
	echo -n "0" > /sys/class/gpio/gpio70/value

	##############################################################
	# IO10 (SAÍDA) *
	if [ ! -d /sys/class/gpio/gpio10 ] ; then
	    echo -n "10" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio10/direction
	chgrp gpio /sys/class/gpio/gpio10/value
	chmod g+rw /sys/class/gpio/gpio10/value

	# Level Shifter GPIO
	if [ ! -d /sys/class/gpio/gpio26 ] ; then
	    echo -n "26" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio26/direction
	echo -n "0" > /sys/class/gpio/gpio26/value

	# Pin Mux 1 GPIO
	if [ ! -d /sys/class/gpio/gpio74 ] ; then
	    echo -n "74" > /sys/class/gpio/export
	fi
	echo -n "0" > /sys/class/gpio/gpio74/value

	##############################################################
	# IO11 (SPI)
	# Level Shifter GPIO
	if [ ! -d /sys/class/gpio/gpio24 ] ; then
	    echo -n "24" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio24/direction
	echo -n "0" > /sys/class/gpio/gpio24/value

	# 22k Pull-Up GPIO
	if [ ! -d /sys/class/gpio/gpio25 ] ; then
	    echo -n "25" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio25/direction

	# Pin Mux 1 GPIO
	if [ ! -d /sys/class/gpio/gpio44 ] ; then
	    echo -n "44" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio44/direction
	echo -n "1" > /sys/class/gpio/gpio44/value

	# Pin Mux 2 GPIO
	if [ ! -d /sys/class/gpio/gpio72 ] ; then
	    echo -n "72" > /sys/class/gpio/export
	fi
	echo -n "0" > /sys/class/gpio/gpio72/value

	##############################################################
	# IO12 (SPI)
	# Level Shifter GPIO
	if [ ! -d /sys/class/gpio/gpio42 ] ; then
	    echo -n "42" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio42/direction
	echo -n "1" > /sys/class/gpio/gpio42/value

	# 22k Pull-Up GPIO
	if [ ! -d /sys/class/gpio/gpio43 ] ; then
	    echo -n "43" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio43/direction

	##############################################################
	# IO13 (SPI)
	# Level Shifter GPIO
	if [ ! -d /sys/class/gpio/gpio30 ] ; then
	    echo -n "30" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio30/direction
	echo -n "0" > /sys/class/gpio/gpio30/value

	# 22k Pull-Up GPIO
	if [ ! -d /sys/class/gpio/gpio31 ] ; then
	    echo -n "31" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio31/direction
	echo -n "0" > /sys/class/gpio/gpio31/value

	# Pin Mux 1 GPIO
	if [ ! -d /sys/class/gpio/gpio46 ] ; then
	    echo -n "46" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio46/direction
	echo -n "1" > /sys/class/gpio/gpio46/value

        chgrp spi /dev/spidev1.0
        chmod g+rw /dev/spidev1.0
    	;;
    stop)
	##############################################################
        # IO3 = pwm1
    	echo -n "0" > /sys/class/pwm/pwmchip0/pwm1/enable
    	echo -n "76" > /sys/class/gpio/unexport
        echo -n "64" > /sys/class/gpio/unexport
	echo -n "17" > /sys/class/gpio/unexport
	echo -n "1" > /sys/class/gpio/gpio16/value
	echo -n "16" > /sys/class/gpio/unexport
	echo -n "1" > /sys/class/pwm/pwmchip0/unexport

	##############################################################
	# IO4
	echo -n "6" > /sys/class/gpio/unexport
	echo -n "in" > /sys/class/gpio/gpio36/direction
	echo -n "36" > /sys/class/gpio/unexport

	##############################################################
	# IO5
	echo -n "0" > /sys/class/gpio/unexport
	echo -n "in" > /sys/class/gpio/gpio18/direction
	echo -n "18" > /sys/class/gpio/unexport
	echo -n "66" > /sys/class/gpio/unexport

	##############################################################
	# IO6
	echo -n "1" > /sys/class/gpio/unexport
	echo -n "in" > /sys/class/gpio/gpio20/direction
	echo -n "20" > /sys/class/gpio/unexport
	echo -n "68" > /sys/class/gpio/unexport

	##############################################################
	# IO7
	echo -n "38" > /sys/class/gpio/unexport

	##############################################################
	# IO8
	echo -n "40" > /sys/class/gpio/unexport

	##############################################################
	# IO9
	echo -n "4" > /sys/class/gpio/unexport
	echo -n "in" > /sys/class/gpio/gpio22/direction
	echo -n "22" > /sys/class/gpio/unexport
	echo -n "70" > /sys/class/gpio/unexport

	##############################################################
	# IO10
	echo -n "10" > /sys/class/gpio/unexport
	echo -n "in" > /sys/class/gpio/gpio26/direction
	echo -n "26" > /sys/class/gpio/unexport
	echo -n "74" > /sys/class/gpio/unexport

	##############################################################
	# IO11
	echo -n "1" > /sys/class/gpio/gpio24/value
	echo -n "24" > /sys/class/gpio/unexport
	echo -n "25" > /sys/class/gpio/unexport
	echo -n "0" > /sys/class/gpio/gpio44/value
	echo -n "44" > /sys/class/gpio/unexport
	echo -n "72" > /sys/class/gpio/unexport

	##############################################################
	# IO12
	echo -n "42" > /sys/class/gpio/unexport
	echo -n "43" > /sys/class/gpio/unexport

	##############################################################
	# IO13
	echo -n "1" > /sys/class/gpio/gpio30/value
	echo -n "30" > /sys/class/gpio/unexport
	echo -n "in" > /sys/class/gpio/gpio31/direction
	echo -n "31" > /sys/class/gpio/unexport
	echo -n "0" > /sys/class/gpio/gpio46/value
	echo -n "46" > /sys/class/gpio/unexport
	;;
    status)
    	echo -n Period:
    	cat /sys/class/pwm/pwmchip0/device/pwm_period
    	echo -n Duty Cicle:
    	cat /sys/class/pwm/pwmchip0/pwm1/duty_cycle
    	echo -n Enable:
    	cat /sys/class/pwm/pwmchip0/pwm1/enable
	;;
    *)
	echo -n "Usage: $0 "
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
